Netflix analysis

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
from textblob import TextBlob

In [2]:
df= pd.read_csv("data/netflix_titles.csv")

In [3]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [4]:
df.shape

(8807, 12)

In [5]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [6]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [8]:
x=df.groupby(["rating"]).size().reset_index(name="counts")

In [9]:
x

      rating  counts
0     66 min       1
1     74 min       1
2     84 min       1
3          G      41
4      NC-17       3
5         NR      80
6         PG     287
7      PG-13     490
8          R     799
9      TV-14    2160
10      TV-G     220
11     TV-MA    3207
12     TV-PG     863
13      TV-Y     307
14     TV-Y7     334
15  TV-Y7-FV       6
16        UR       3

In [10]:
piechart=px.pie(x, values='counts',names='rating',title='Distibution of content ratings in netflix')

In [11]:
piechart.show()

In [12]:
year_wise_movies= df.groupby(['release_year']).size().reset_index(name="no_of_shows")

In [13]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [14]:
df["director"]=df["director"].fillna("Directors not specified")

In [15]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Directors not specified,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Directors not specified,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Directors not specified,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [16]:
director_list=pd.DataFrame()

In [17]:
print(director_list)

Empty DataFrame
Columns: []
Index: []

In [18]:
director_list=df["director"].str.split(',',expand=True).stack()

In [19]:
director_list

0     0            Kirsten Johnson
1     0    Directors not specified
2     0            Julien Leclercq
3     0    Directors not specified
4     0    Directors not specified
                    ...
8802  0              David Fincher
8803  0    Directors not specified
8804  0            Ruben Fleischer
8805  0               Peter Hewitt
8806  0                Mozez Singh
Length: 9612, dtype: object

In [20]:
director_list=director_list.to_frame()

In [21]:
director_list.columns=['Director']

In [22]:
print(director_list)

                       Director
0    0          Kirsten Johnson
1    0  Directors not specified
2    0          Julien Leclercq
3    0  Directors not specified
4    0  Directors not specified
...                         ...
8802 0            David Fincher
8803 0  Directors not specified
8804 0          Ruben Fleischer
8805 0             Peter Hewitt
8806 0              Mozez Singh

[9612 rows x 1 columns]

In [23]:
no_of_directors=director_list.groupby(['Director']).size().reset_index(name="count")

In [24]:
no_of_directors

                       Director  count
0                Aaron Moorhead      2
1                   Aaron Woolf      1
2      Abbas Alibhai Burmawalla      1
3              Abdullah Al Noor      1
4           Abhinav Shiv Tiwari      1
...                         ...    ...
5116                Çagan Irmak      1
5117           Ísold Uggadóttir      1
5118        Óskar Thór Axelsson      1
5119           Ömer Faruk Sorak      2
5120               Şenol Sönmez      2

[5121 rows x 2 columns]

In [25]:
unique_directors=no_of_directors.sort_values(by='count', ascending=False)

In [26]:
unique_directors=unique_directors[unique_directors.Director!='Directors not specified']

In [27]:
top_5_directors=unique_directors.head(5)

In [28]:
top_5_directors

           Director  count
4021  Rajiv Chilaka     22
261       Jan Suter     18
4068    Raúl Campos     18
3236   Marcus Raboy     16
4652    Suhas Kadav     16

In [29]:
top_5_directors=top_5_directors.sort_values(by="count")
barchart=px.bar(top_5_directors, x="count",y="Director",title="Top five directors and number of movies")

In [30]:
barchart.show()

In [31]:
df['release_year']

0       2020
1       2021
2       2021
3       2021
4       2021
        ...
8802    2007
8803    2018
8804    2009
8805    2006
8806    2015
Name: release_year, Length: 8807, dtype: int64

In [32]:
df['cast']=df['cast'].fillna("No cast specified")

In [33]:
df.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,No cast specified,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Directors not specified,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Directors not specified,No cast specified,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Directors not specified,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...

In [34]:
total_number_of_cast=pd.DataFrame()

In [35]:
print(total_number_of_cast)

Empty DataFrame
Columns: []
Index: []

In [36]:
total_number_of_cast=df['cast'].str.split(',',expand=True).stack()

In [37]:
total_number_of_cast=total_number_of_cast.to_frame()

In [38]:
total_number_of_cast

                             0
0    0       No cast specified
1    0              Ama Qamata
     1             Khosi Ngema
     2           Gail Mabalane
     3          Thabang Molaba
...                        ...
8806 3        Manish Chaudhary
     4            Meghna Malik
     5           Malkeet Rauni
     6          Anita Shabdish
     7   Chittaranjan Tripathy

[64951 rows x 1 columns]

In [39]:
total_number_of_cast.columns=['casts']

In [40]:
total_number_of_cast=total_number_of_cast.groupby('casts').size().reset_index(name='count_of_cast')

In [41]:
total_number_of_cast

                        casts  count_of_cast
0                         Jr.              2
1       "Riley" Lakdhar Dridi              1
2                'Najite Dede              1
3                    2 Chainz              1
4                        2Mex              1
...                       ...            ...
39292         İbrahim Büyükak              1
39293        İbrahim Çelikkol              1
39294             Şahin Irmak              1
39295          Şükrü Özyıldız              1
39296            Ṣọpẹ́ Dìrísù              1

[39297 rows x 2 columns]

In [42]:
top_casts=total_number_of_cast.sort_values(by=['count_of_cast'],ascending=False)

In [43]:
top_casts=top_casts[top_casts.casts!='No cast specified']

In [44]:
top_casts

                   casts  count_of_cast
2612         Anupam Kher             39
26941       Rupa Bhimani             31
30303   Takahiro Sakurai             30
15541      Julie Tejwani             28
23624            Om Puri             27
...                  ...            ...
39292    İbrahim Büyükak              1
39293   İbrahim Çelikkol              1
39294        Şahin Irmak              1
39295     Şükrü Özyıldız              1
39264           Zhang Yi              1

[39296 rows x 2 columns]

In [45]:
top_5_casts=top_casts.head()

In [46]:
top_5_casts=top_5_casts.sort_values(by='count_of_cast')

In [47]:
barchart=px.bar(top_5_casts, x='count_of_cast', y='casts',title='Top 5 casts of Netflix shows')

In [48]:
barchart.show()

In [49]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,No cast specified,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Directors not specified,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Directors not specified,No cast specified,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Directors not specified,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,Directors not specified,No cast specified,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [50]:
df1=df[['type','release_year']]

In [51]:
df1

         type  release_year
0       Movie          2020
1     TV Show          2021
2     TV Show          2021
3     TV Show          2021
4     TV Show          2021
...       ...           ...
8802    Movie          2007
8803  TV Show          2018
8804    Movie          2009
8805    Movie          2006
8806    Movie          2015

[8807 rows x 2 columns]

In [52]:
df1=df1.rename(columns={'type':'Content Type','release_year':'Release Year'})

In [53]:
df1

     Content Type  Release Year
0           Movie          2020
1         TV Show          2021
2         TV Show          2021
3         TV Show          2021
4         TV Show          2021
...           ...           ...
8802        Movie          2007
8803      TV Show          2018
8804        Movie          2009
8805        Movie          2006
8806        Movie          2015

[8807 rows x 2 columns]

In [54]:
no_of_release=df1.groupby(['Release Year','Content Type']).size().reset_index(name='count_of_movies')

In [55]:
no_of_release

     Release Year Content Type  count_of_movies
0            1925      TV Show                1
1            1942        Movie                2
2            1943        Movie                3
3            1944        Movie                3
4            1945        Movie                3
..            ...          ...              ...
114          2019      TV Show              397
115          2020        Movie              517
116          2020      TV Show              436
117          2021        Movie              277
118          2021      TV Show              315

[119 rows x 3 columns]

In [56]:
no_of_release=no_of_release[no_of_release['Release Year']>=2000]

In [57]:
no_of_release

     Release Year Content Type  count_of_movies
75           2000        Movie               33
76           2000      TV Show                4
77           2001        Movie               40
78           2001      TV Show                5
79           2002        Movie               44
80           2002      TV Show                7
81           2003        Movie               51
82           2003      TV Show               10
83           2004        Movie               55
84           2004      TV Show                9
85           2005        Movie               67
86           2005      TV Show               13
87           2006        Movie               82
88           2006      TV Show               14
89           2007        Movie               74
90           2007      TV Show               14
91           2008        Movie              113
92           2008      TV Show               23
93           2009        Movie              118
94           2009      TV Show               34
95           2010        Movie              154
96           2010      TV Show               40
97           2011        Movie              145
98           2011      TV Show               40
99           2012        Movie              173
100          2012      TV Show               64
101          2013        Movie              225
102          2013      TV Show               63
103          2014        Movie              264
104          2014      TV Show               88
105          2015        Movie              398
106          2015      TV Show              162
107          2016        Movie              658
108          2016      TV Show              244
109          2017        Movie              767
110          2017      TV Show              265
111          2018        Movie              767
112          2018      TV Show              380
113          2019        Movie              633
114          2019      TV Show              397
115          2020        Movie              517
116          2020      TV Show              436
117          2021        Movie              277
118          2021      TV Show              315

In [58]:
linechart=px.line(no_of_release, x='Release Year', y='count_of_movies',color='Content Type',title="No of release per year since 2000")

In [59]:
linechart.update_xaxes(
    tickmode='linear',
    dtick=1
)
linechart.show()

In [60]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,No cast specified,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Directors not specified,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Directors not specified,No cast specified,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Directors not specified,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,Directors not specified,No cast specified,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [61]:
df2=df[['release_year',"description"]]

In [62]:
df2

      release_year                                        description
0             2020  As her father nears the end of his life, filmm...
1             2021  After crossing paths at a party, a Cape Town t...
2             2021  To protect his family from a powerful drug lor...
3             2021  Feuds, flirtations and toilet talk go down amo...
4             2021  In a city of coaching centers known to train I...
...            ...                                                ...
8802          2007  A political cartoonist, a crime reporter and a...
8803          2018  While living alone in a spooky town, a young g...
8804          2009  Looking to survive in a world taken over by zo...
8805          2006  Dragged from civilian life, a former superhero...
8806          2015  A scrappy but poor boy worms his way into a ty...

[8807 rows x 2 columns]

In [63]:
for index,row in df2.iterrows():
    d=row['description']
    testimonial=TextBlob(d)
    p=testimonial.sentiment.polarity
    if p==0:
        sent="Neutral"
    elif p>0:
        sent="Positive"
    else:
        sent="Negative"
    df2.loc[[index,2],'Sentiment']=sent

C:\Users\DELL\AppData\Local\Temp\ipykernel_23212\1373636990.py:11: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [64]:
df2

,release_year,description,Sentiment
0,2020,"As her father nears the end of his life, filmm...",Positive
1,2021,"After crossing paths at a party, a Cape Town t...",Neutral
2,2021,To protect his family from a powerful drug lor...,Negative
3,2021,"Feuds, flirtations and toilet talk go down amo...",Negative
4,2021,In a city of coaching centers known to train I...,Neutral
...,...,...,...
8802,2007,"A political cartoonist, a crime reporter and a...",Negative
8803,2018,"While living alone in a spooky town, a young g...",Positive
8804,2009,Looking to survive in a world taken over by zo...,Neutral
8805,2006,"Dragged from civilian life, a former superhero...",Positive
8806,2015,A scrappy but poor boy worms his way into a ty...,Negative

In [65]:
df2=df2[df2['release_year']>=2000]

In [66]:
df2

,release_year,description,Sentiment
0,2020,"As her father nears the end of his life, filmm...",Positive
1,2021,"After crossing paths at a party, a Cape Town t...",Neutral
2,2021,To protect his family from a powerful drug lor...,Negative
3,2021,"Feuds, flirtations and toilet talk go down amo...",Negative
4,2021,In a city of coaching centers known to train I...,Neutral
...,...,...,...
8802,2007,"A political cartoonist, a crime reporter and a...",Negative
8803,2018,"While living alone in a spooky town, a young g...",Positive
8804,2009,Looking to survive in a world taken over by zo...,Neutral
8805,2006,"Dragged from civilian life, a former superhero...",Positive
8806,2015,A scrappy but poor boy worms his way into a ty...,Negative

In [67]:
sentiment_count=df2.groupby(['release_year','Sentiment']).size().reset_index(name="Total Count")

In [68]:
sentiment_count

    release_year Sentiment  Total Count
0           2000  Negative           11
1           2000   Neutral            6
2           2000  Positive           20
3           2001  Negative           14
4           2001   Neutral            5
..           ...       ...          ...
61          2020   Neutral          161
62          2020  Positive          519
63          2021  Negative          164
64          2021   Neutral           85
65          2021  Positive          343

[66 rows x 3 columns]

In [69]:
barchart=px.bar(sentiment_count, x="release_year",y="Total Count",color="Sentiment", title='Sentimental analysis of Netflix shows')

In [70]:
barchart.show()